[workspace]
members = [
    "caer_compiler",
    "caer_infer",
    "caer_ir",
    "caer_runtime",
    "caer_types",
    "caer_util",
    "cstub_bindgen_macro",
    "llvm_stackmaps",
    "rustc_dwarf",
    "rustc_unwind",
]
