[package]
authors = ["Colm Ó hIcí <colmohici@gmail.com>"]
edition = "2018"
name = "ldc"
version = "0.1.0"

[dependencies]

[dependencies.dreammaker]
path = "../SpacemanDMM/src/dreammaker"

[dependencies.indexed_vec]
path = "../indexed_vec"
default-features = false

[dependencies.inkwell]
branch = "llvm7-0"
git = "https://github.com/TheDan64/inkwell"
