edition = "2021"

imports_granularity = "Module"
group_imports = "StdExternalCrate"
match_block_trailing_comma = true
reorder_impl_items = true
use_field_init_shorthand = true

# maybe not
fn_args_layout = "Compressed"
