[package]
name = "caer_runtime"
version = "0.1.0"
authors = ["Colm Ó hIcí <colmohici@gmail.com>"]
edition = "2018"

[lib]
name = "caer_runtime"
crate-type = ["cdylib", "lib"]

[dependencies]
bincode = "1.2.1"
serde = { version = "1.0", features = ["derive"] }

[dependencies.dreammaker]
git = "https://github.com/SpaceManiac/SpacemanDMM"

[dependencies.cstub_bindgen_macro]
path = "../cstub_bindgen_macro"

[dependencies.indexed_vec]
path = "../indexed_vec"
