[package]
authors = ["Colm Ó hIcí <colmohici@gmail.com>"]
name = "aed_common"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = "1.0.37"
serde_cbor = "0.8.2"
serde_derive = "1.0.37"
serde_json = "1.0.13"
