[package]
authors = ["Colm Ó hIcí <colmohici@gmail.com>"]
name = "aed_common"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.125"
serde_cbor = "0.11.1"
serde_derive = "1.0.125"
serde_json = "1.0.64"
