[package]
name = "caer_util"
version = "0.1.0"
authors = ["Colm Ó hIcí <colmohici@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
index_vec = { version = "0.1.2", features = ["serde"] }
