[package]
authors = ["Colm Ó hIcí <git@ohici.ie>"]
edition = "2018"
name = "caer_compiler"
version = "0.1.0"
license = "GPL-3.0-or-later"

[dependencies]
caer_codegen_llvm = { path = "../caer_codegen_llvm" }
caer_frontend = { path = "../caer_frontend" }
